### ISSUE TITLE
Using source maps on dev environment

### ISSUE THREAD

**Issue by dziga** [fruskac/map#11]
While working on an issue, I have noticed that all scripts and styles are 'minified', which makes it harder to debug with. Are you planning to introduce source maps (for dev environment only) perhaps?

**Comment by mladenplavsic** [comment]
Sure! As production code is minified and inlined, adding something simple like https://www.npmjs.com/package/gulp-sourcemaps#write-inline-source-maps will help a lot.

**Comment by dziga** [comment]
Tnx :)

Wanted to add them myself, but thanks for the effort.
