### ISSUE TITLE
"addClass" util function is adding same CSS class multiple times

### ISSUE THREAD

**Issue by mladenplavsic** [fruskac/map#5]
This is visible as you click different "activities" on marker which belongs to multiple categories

**Comment by dziga** [comment]
In util function addClass (https://github.com/fruskac/map/blob/master/src/js/util.js#L15) there is no check if element has class which is being added. 

Perhaps adding function hasClass which can be utilized in other places and which can be use to fix this particular problem?

**Comment by mladenplavsic** [comment]
@dziga That's a good idea! Planning to send a pull request?

**Comment by dziga** [comment]
Sure, I'll take this one. Good one to start with (setting up env etc.)
